### ISSUE TITLE
Editor's review

### ISSUE THREAD

**Issue by santisoler** [pinga-lab/tesseroid-variable-density#36]
I'll list a small list with editor's remarks on the first submitted manuscript.
See [`editors_revision.md`](https://github.com/pinga-lab/tesseroid-variable-density/blob/master/editors_revision.md) for detailed revision of the manuscript.

- [ ] 1) Incorporate Li and Denker (2018)
- [ ] 2) "arbitrary" density function issue: specify continuous and smooth.
- [ ] 3) Include reference to Anderson (1976)
- [ ] 4) Homogenize gravitational quantities (gradient, tensor, acceleration)
- [ ] 5) P3, L49: "...fields generated by the analytical solution of a spherical shell."
- [ ] 6) P4, L25 and elsewhere "first- and second-order derivatives"
- [ ] 7) Undefined tesseroid boundaries variables
- [ ] 8) How to compute GLQ nodes and weights
- [ ] 9) P5, L49: "... and W^r_i, W^\phi_j, W^\lambda_k are the quadrature weights."
- [ ] 10) P7, L16: I am not sure what is meant by "offending dimensions".
- [ ] 11) P9, L37: "For further iterations".
- [ ] 12) P9, L47: Second dot at the end of line.
- [ ] 13) Motivation of selected parameters (tesseroid discretization, computation grid sizes/regions/heights and coefficients for the linear and exponential density function).
- [ ] 14) Eq. (25): b instead of c?
- [ ] 15) Discussion on Figure 3 on four scenarios (4 different grids)
- [ ] 16) P14, L43: "... equal to the linear density case"
- [ ] 17) Information on computational load.
- [ ] 18) Extend section 4 with discussion on Neuquen Basin results
- [ ] 19) P17, L44: Please add a reference to the statement "These values are in agreement with previous results ...".
- [ ] 20) P20, L30: "z-axis"
- [ ] 21) Eq. (A.9): Missing dot at the end of line.
- [ ] 22) P21, L33: "... expressions for the gravitational potential with different"
- [ ] 23) To help the reader, it is useful to additionally provide a chapter or page number
for references based on text books like Hildebrand (1987).

**Comment by leouieda** [comment]
@santis19 best to remove the markdown file from the repo. Reviews a bit of a gray area regarding confidentiality. We can open issues with things to resolve but it's best to be prudent.

**Comment by santis19** [comment]
@leouieda Ok, I've remove it from all branches.
