### ISSUE TITLE
Add paper DOI link to figshare

### ISSUE THREAD

**Issue by leouieda** [pinga-lab/tesseroid-variable-density#66]
Now that we have a DOI for the paper, we should add it to the metadata (links and description) of the figshare archive.

**Comment by santisoler** [comment]
Done! 
I've added a little sentence on the description pointing towards the version of record (I copied a sentence from [Oxford's Author self-archiving policies](https://academic.oup.com/journals/pages/access_purchase/rights_and_permissions/author_self_archiving_policy)).
And also added the DOI to the references.

[Check it out](https://figshare.com/articles/Source_code_and_data_for_Gravitational_field_calculation_in_spherical_coordinates_using_variable_densities_in_depth_/8239622) and tell me if it meets your expectations
