### ISSUE TITLE
Missing "Makefile" file at tesseroid-variable-density/code/tesseroid_density/

### ISSUE THREAD

**Issue by xiaoledeng** [pinga-lab/tesseroid-variable-density#73]
I think it may miss the "Makefile" file at tesseroid-variable-density/code/tesseroid_density/ as: 

`Makefile`: File to automate the compilation of the `tesseroid.pyx` code.

**Comment by santisoler** [comment]
Hi @xiaoledeng!

Thanks for opening this Issue.
It seems the `code/tesseroid_density/README.md` file is wrong. The `tesseroid_density` package is supposed to be built from `code/Makefile`, which uses `pip` to install it, following the instructions on `code/setup.py`.

I'll change the instructions on the `code/tesseroid_density/README.md`.

But, this doesn't change the fact that you are having issues building and installing the `tesseroid_density` package, right?
If that's the case, would you mind giving me more information about what's going on?

**System information**

* Operating system:
* Python installation (Anaconda, system, ETS):
* Version of Python:
* If using conda, paste the output of `conda list` below:

**Full code that generated the error**

Please copy the code that is generating the error.

**Comment by xiaoledeng** [comment]
Thanks for your reply.

When I type `make build` at tesseroid-variable-density-master/code, it happens: 

➜  make build
pip install --no-deps -e .
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Obtaining file:///Users/shalom/Documents/Paper/2020Deng-JG2ab/tesseroid-variable-density-master/code
Installing collected packages: tesseroid-density
  Running setup.py develop for tesseroid-density
Successfully installed tesseroid-density

It seems that the `tesseroid-density` is installed. Thanks a lot.

**Comment by santisoler** [comment]
Glad it's working! :tada:
I think we should close this Issue.
If you have any further problem running the scripts (or understanding the code), don't hesitate to ask for help!
